DROP TABLE IF EXISTS dbo.nota
DROP TABLE IF EXISTS dbo.empresa

CREATE TABLE dbo.empresa(
	Id INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_EmpresaId PRIMARY KEY,
	Cnpj VARCHAR(14) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Faturamento DECIMAL(10,2) NOT NULL,
	Ramo INT NOT NULL
);

CREATE TABLE dbo.nota(
	Id INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_NotaId PRIMARY KEY,
	Numero INT UNIQUE,
	Valor DECIMAL(10,2) NOT NULL,
	DataVencimento DATE NOT NULL,
	EmpresaId INT,
	CONSTRAINT fk_EmpresaId FOREIGN KEY (EmpresaId) REFERENCES dbo.empresa(Id)
);